### ISSUE TITLE
Mask GroundTruth

### ISSUE THREAD

**Issue by ChenHsing** [henghuiding/MeViS#4]
I download the mask_dict.json from the google cloud, however, there seems to be some Encoding error， could you please provide a Annotation folder such as Youtube-vos and Davis?

**Comment by henghuiding** [comment]
Hi,

Thank you for your attention.


Please kindly verify the SHA256 sum of the mask_dict.json files to ensure the data intergrity:
```
f9d9b01a2a6d7a004e2e7a664ce2b9b1576218e975030f8e4df4f66111fb253f train/mask_dict.json
6e711a3f713cd95a825f536323e434b4d80f85a8e4e66d0cd662408e8779db50 valid_u/mask_dict.json
```
There should be no encoding error when using our code. 

Additionally, we also provide [ReferFormer_dataloader.py](https://github.com/henghuiding/MeViS/blob/main/ReferFormer_dataset.py) for reading .json, with which you can train [ReferFormer](https://github.com/wjn922/ReferFormer/tree/main/datasets) on MeViS dataset.

**Comment by ChenHsing** [comment]
But could you please provide a script to convert the mask_dict.json to mask annotation with jpg？ I have some trouble in this step.
